version: '2'
services:
  aula2:
    image: oficina-docker:aula2-volumes
    build: .
    ports: 
     - 5020:5000
    volumes:
     - .:/usr/src
     - aula2-logs:/tmp
  nginx:
    image: nginx:alpine
    ports:
     - 80:80
  db:
    image: postgres:9.6
    ports:
     - 5432:5432

  cache:
    image: memcached

volumes:
  aula2-logs:
    external: true
